'use client'
import { Canvas,useFrame } from '@react-three/fiber'
import { Environment,MeshTransmissionMaterial,PerspectiveCamera } from '@react-three/drei'
import { Bloom,EffectComposer,Noise,Vignette } from '@react-three/postprocessing'
import { Suspense,useMemo,useRef } from 'react'
import * as THREE from 'three'
import type { ExperienceRefs } from '@/components/experience/ExperienceMotion'
const smooth=(a:number,b:number,s:number)=>a+(b-a)*s
function Core({motion,service}:{motion:ExperienceRefs;service:number}){const g=useRef<THREE.Group>(null),rings=useRef<THREE.Mesh[]>([]),particles=useRef<THREE.Points>(null);const pts=useMemo(()=>{const a=new Float32Array(560*3);for(let i=0;i<a.length;i+=3){const t=Math.random()*Math.PI*2,r=.3+Math.random()*2.8;a[i]=Math.cos(t)*r;a[i+1]=(Math.random()-.5)*4;a[i+2]=Math.sin(t)*r}return a},[]);useFrame((s,dt)=>{if(!g.current)return;const p=motion.progress.current;const v=Math.min(1,Math.abs(motion.velocity.current)*.02);const chapter=Math.min(1,Math.max(0,(p-.06)/.56));const expand=chapter<.25?chapter*2:Math.min(1,(chapter-.25)*1.35);g.current.rotation.y+=dt*(.12+v*.85);g.current.rotation.x=smooth(g.current.rotation.x,motion.pointer.current.y*.15+Math.sin(s.clock.elapsedTime*.35)*.08,.05);g.current.rotation.z=smooth(g.current.rotation.z,p*.7,.03);g.current.position.set(motion.pointer.current.x*.18,p*.4,0);g.current.scale.setScalar(.18+Math.min(1,p/.17)*.82+expand*.65);rings.current.forEach((m,i)=>{if(!m)return;const q=expand*(.65+i*.18)+service*.035;m.position.set(Math.sin(i*1.8+p*9)*q,Math.cos(i*2+p*7)*q*.55,Math.cos(i+p*5)*q);m.rotation.x+=dt*(.09+i*.015);m.rotation.z=smooth(m.rotation.z,(p*2+i)*.7,.025)});if(particles.current){particles.current.rotation.y+=dt*(.015+p*.06);particles.current.scale.setScalar(.35+expand*1.9)}});const metal=['#8e948d','#e9ece4','#5d625d','#b7c0b1','#d7dfd0'];return <group ref={g}>{[0,1,2,3,4].map(i=><mesh key={i} ref={e=>{if(e)rings.current[i]=e}} rotation={[i*.37,i*.63,0]}><torusGeometry args={[1.05+i*.22,.035+i*.008,12,96]}/><meshStandardMaterial color={metal[i]} metalness={.96} roughness={.19+i*.06}/></mesh>)}<mesh rotation={[.62,.2,.6]}><icosahedronGeometry args={[.82,3]}/><MeshTransmissionMaterial transmission={.4} thickness={.48} roughness={.06} color="#d9e0d1" chromaticAberration={.025}/></mesh><mesh scale={.46} rotation={[.3,.8,.3]}><boxGeometry args={[1,1,1]}/><meshStandardMaterial color="#101310" metalness={1} roughness={.16}/></mesh><points ref={particles}><bufferGeometry><bufferAttribute attach="attributes-position" args={[pts,3]}/></bufferGeometry><pointsMaterial color="#dde6d4" size={.012} transparent opacity={.72} sizeAttenuation depthWrite={false}/></points></group>}
function Network({motion}:{motion:ExperienceRefs}){const g=useRef<THREE.Group>(null);const lines=useMemo(()=>{const a:number[]=[];const n=7;for(let i=0;i<n;i++){const ai=i/n*Math.PI*2;for(let j=i+1;j<n;j++){if((j-i)%2){const aj=j/n*Math.PI*2;a.push(Math.cos(ai)*2,Math.sin(ai)*1.3,-.7,Math.cos(aj)*2,Math.sin(aj)*1.3,-.7)}}}return new Float32Array(a)},[]);useFrame((_,dt)=>{if(g.current){const p=motion.progress.current;g.current.visible=p>.37;g.current.rotation.z+=dt*.018;g.current.scale.setScalar(Math.max(0,(p-.33)*2.5))}});return <group ref={g} visible={false}><lineSegments><bufferGeometry><bufferAttribute attach="attributes-position" args={[lines,3]}/></bufferGeometry><lineBasicMaterial color="#c8d2c0" transparent opacity={.26}/></lineSegments>{Array.from({length:7},(_,i)=>{const t=i/7*Math.PI*2;return <mesh key={i} position={[Math.cos(t)*2,Math.sin(t)*1.3,-.7]}><sphereGeometry args={[.07,12,12]}/><meshStandardMaterial color="#dce8ce" emissive="#819a59" emissiveIntensity={.8}/></mesh>})}</group>}
function Scene({motion,service}:{motion:ExperienceRefs;service:number}){const camera=useRef<THREE.PerspectiveCamera>(null);useFrame((_,dt)=>{if(camera.current){const p=motion.progress.current;const z=8-p*3.4;camera.current.position.z=smooth(camera.current.position.z,z,dt*1.5);camera.current.position.x=smooth(camera.current.position.x,motion.pointer.current.x*.24,dt*1.8);camera.current.lookAt(0,0,0)}});return <><color attach="background" args={['#070806']}/><fog attach="fog" args={['#070806',5,17]}/><PerspectiveCamera ref={camera} makeDefault position={[0,0,8]} fov={35}/><ambientLight intensity={.18}/><spotLight position={[4,5,4]} intensity={58} angle={.37} penumbra={1} color="#f1f4ec"/><pointLight position={[-4,-1,2]} intensity={18} color="#7e8c74"/><Core motion={motion} service={service}/><Network motion={motion}/><Environment preset="warehouse"/><EffectComposer multisampling={0}><Bloom intensity={.32} luminanceThreshold={.72} mipmapBlur/><Noise opacity={.022}/><Vignette darkness={.75} offset={.22}/></EffectComposer></>}
export function CreationWorld({motion,service}:{motion:ExperienceRefs;service:number}){return <Canvas dpr={[1,1.65]} gl={{antialias:false,powerPreference:'high-performance'}}><Suspense fallback={null}><Scene motion={motion} service={service}/></Suspense></Canvas>}